### ISSUE TITLE
Maintenance?

### ISSUE THREAD

**Issue by kokujin** [adityamukho/sails-nedb#4]
Is this lib still being maintained? I was actually going to develop a neDB adapter and I found this by chance, its not listed on the Sails or Waterline sites as a community adapter.

**Comment by adityamukho** [comment]
I'm not actively maintaining this repository at present due to a lack of time, but I can still process any PRs that come along :).

**Comment by kokujin** [comment]
Hey @adityamukho , I just noticed that there is a third neDb adapter, actually, you were asked if you would like to merge both repositories, can you give the author a definitive answer, based on that  we can see if there is anything else that needs further development.

https://github.com/adityamukho/sails-nedb/issues/1 --> https://github.com/andyhu/waterline-nedb

I will delete my neDB adapter respository after that and contribute to the merged version.
